---
title: "ANA 515 Assignment 1"
author: "Michael Eniolade"
date: "3/16/2022"
output:
  html_document:
    theme: readable
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyverse")
#install.packages("knitr")
#install.packages("bslib")
#install.packages("dplyr")
library(tidyverse)
library(knitr)
library(bslib)
library(dplyr)
```


```{r gun_deaths, include=TRUE, cache = FALSE}
url <- "https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv"
gun_deaths <- read_csv(url)
glimpse(gun_deaths)
```
```{r youth, include=TRUE, cache = FALSE}
youth<-filter(gun_deaths, age<=65)
summary(youth)
```
```{r echo = FALSE}
gun_d<-data.frame(gun_deaths)
youth_d<-data.frame(youth)
or_tot<-nrow(gun_d)
diff<-or_tot-nrow(youth_d)
```

## Gun Deaths by age

```{r youth_d, include=TRUE, cache = FALSE}
youth_d%>%
  ggplot(aes(age))+geom_freqpoly(binwidth=1)
```

## Gun Deaths by race

We have data about `r or_tot` individuals killed by guns. Only `r diff` are older than 65. 



```{r youth_ds, include=TRUE, cache = FALSE}
youth_d%>%
  ggplot(aes(fct_infreq(race)%>%fct_rev()))+geom_bar()+coord_flip()+
  labs(x="Victim race")
```
